### ISSUE TITLE
Publish to public maven repository

### ISSUE THREAD

**Issue by andrew00x** [opensearch-project/opensearch-testcontainers#15]
Could it be published to any public maven repository? If it is already published somewhere, please reflect this in docs. According to _build.gradle.kts_ it should be published to https://repo.maven.apache.org/maven2 but there is nothing [here](https://repo.maven.apache.org/maven2/org/opensearch/)

**Comment by dblock** [comment]
+1 anyone should feel free to contribute GHA workflows for this

**Comment by sharp-pixel** [comment]
Looks like there is still nothing in maven public repo, so the issue should not be closed yet.
