### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-testcontainers#67]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by dblock** [comment]
@gaiksaya @peterzhuamazon @ginkel you've all contributed to this repo - any interest in helping co-maintain it?

**Comment by dblock** [comment]
Verified that permissions are correct, MAINTAINERS and CODEOWNERS as well.

![Screenshot 2023-05-03 at 5 31 48 PM](https://user-images.githubusercontent.com/542335/236054481-33329bd9-c042-4af6-aca8-49174dcac291.png)

**Comment by peterzhuamazon** [comment]
> @gaiksaya @peterzhuamazon @ginkel you've all contributed to this repo - any interest in helping co-maintain it?



> @gaiksaya @peterzhuamazon @ginkel you've all contributed to this repo - any interest in helping co-maintain it?

Yes

**Comment by dblock** [comment]
@reta I'm going to add @peterzhuamazon, cool?

**Comment by reta** [comment]
> @reta I'm going to add @peterzhuamazon, cool?

Totally, thanks @dblock !
